### ISSUE TITLE
Замечания по lw2

### ISSUE THREAD

**Issue by lulldev** [woody21978/lab#2]
**Task2**

Форма без стилей должна быть в master, со стилями в отдельной ветке

**Comment by lulldev** [comment]
```html
    <div class="btn">
      <button class="submit" type="submit">Отправить</button>
    </div>
```

btn - не точное название, лучше что то типа *_block.

**Comment by lulldev** [comment]
**Task3**

1. videoBlockOne - непонятное имя переменной

2. в коде:

```js
      if (username == "") {
```
a) ковычки `'`
b) лучше использовать строгое сравнение

3. в коде ниже

```
      if (username == "") {
        alert("Введите Имя пользователя");
        return false;
      } else if (message == "") {
        alert("Введите Текст комментария");
        return false;
      }
```

попробуйте написать короче (избавиться от одного из 2 alert/return)

**Comment by lulldev** [comment]
Стилизуйте общие теги (body, p, img), но специальные теги лучше стилизовать по классам

```css
form {
  display: flex;
  flex-direction: column;
}
input, textarea {
  padding: 7px 10px;
  border: 2px solid #333;
  margin-bottom: 15px;
  font-size: 18px;
}
textarea {
  font-size: 16px;
}
```
